# Generated by Django 5.2.7 on 2025-11-12 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloPrediccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_modelo', models.CharField(default='Random Forest Regressor', max_length=100)),
                ('fecha_entrenamiento', models.DateTimeField(auto_now_add=True)),
                ('r2_score', models.FloatField(blank=True, null=True)),
                ('mse', models.FloatField(blank=True, null=True)),
                ('version', models.CharField(default='1.0', max_length=20)),
            ],
            options={
                'db_table': 'modelo_prediccion',
            },
        ),
        migrations.CreateModel(
            name='PrediccionVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=20)),
                ('categoria', models.CharField(blank=True, max_length=100, null=True)),
                ('valor_predicho', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_prediccion', models.DateTimeField(auto_now_add=True)),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predicciones', to='prediccion.modeloprediccion')),
            ],
            options={
                'db_table': 'prediccion_venta',
            },
        ),
    ]
